import os
import urllib2
import zipfile

#script for downloading all objects from KIT database

pathz="http://i61p109.ira.uka.de/ObjectModelsWebUI/tmp.php?id=" 
postID="&kat=DCMeshes&dp=Objects/"
postobj="/meshes.zip"
mountloc="/mnt/terastation/shape_data/"

ID=0
def getfiles(obj):
	global ID
	ID+=1
	print 'starting '+obj+' ID='+str(ID)
	if not os.path.exists(mountloc+'KIT/'+obj):
		os.makedirs(mountloc+'KIT/'+obj)
	downloadpath=pathz+str(ID)+postID+obj+postobj


	req=urllib2.Request(downloadpath)
	resp=urllib2.urlopen(req)
	html=resp.read()
	lf=mountloc+'KIT/'+obj+"/meshes.zip"
	lfopen=open(lf,"wb")
	lfopen.write(html)
	lfopen.close()
	toextract=zipfile.ZipFile(lf,'r')
	toextract.extractall(mountloc+'KIT/'+obj+"/")
	toextract.close()
	os.remove(lf)
	

# getfiles('OrangeMarmelade')
# getfiles('BlueSaltCube')
# getfiles('YellowSaltCube')
# getfiles('FruitTea')
# getfiles('GreenSaltCylinder')
# getfiles('MashedPotatoes')
# getfiles('YellowSaltCylinder')
# getfiles('Rusk')
# getfiles('Knaeckebrot')
# getfiles('Amicelli')
# getfiles('HotPot')
# getfiles('YellowSaltCube2')
# getfiles('Sauerkraut')
# getfiles('LivioClassicOil')
# getfiles('LivioSunflowerOil')
# getfiles('DanishHam')
# getfiles('SauerkrautSmall')
# getfiles('HeringTin')
# getfiles('RavioliLarge')
# getfiles('InstantSoup')
# getfiles('Toothpaste')
# getfiles('HotPot2')
# getfiles('KnaeckebrotRye')
# getfiles('CeylonTea')
# getfiles('Rice')
# getfiles('FennelTea')
# getfiles('MuesliBars')
# getfiles('Deodorant')
# ID=28
# getfiles('HygieneSpray')
# getfiles('PowderedSugar')
# getfiles('CondensedMilk')
# getfiles('SoftCakeOrange')
# getfiles('CoffeeFilters')
# getfiles('PineappleSlices')
# getfiles('FruitDrink')
# getfiles('InstantIceCoffee')
# getfiles('ChoppedTomatoes')
# getfiles('MilkDrinkVanilla')
# getfiles('WhippedCream')
ID=40
getfiles('PotatoeStarch')
getfiles('InstantDumplings')
getfiles('ChocolateBars')
getfiles('JamSugar')
getfiles('YellowSaltCylinderSmall')
getfiles('InstantMousse')
getfiles('TomatoSauce')
getfiles('PowderedSugarMill')
getfiles('SauceThickener')
getfiles('CoffeeFilters2')
getfiles('ShowerGel')
getfiles('Margarine')
getfiles('MilkRice')
getfiles('Patches')
getfiles('PotatoeDumplings')
getfiles('CoughDropsLemon')
getfiles('CoughDropsHoney')
getfiles('CoughDropsBerries')
getfiles('FruitBars')
getfiles('PatchesSensitive')
getfiles('SardinesCan')
getfiles('DropsOrange')
getfiles('DropsCherry')
getfiles('FizzyTablets')
getfiles('FizzyTabletsCalcium')
getfiles('PotatoeSticks')
getfiles('Wafflerolls')
getfiles('Shampoo')
getfiles('HamburgerSauce')
getfiles('RuskWholemeal')
getfiles('NutCandy')
getfiles('KoalaCandy')
getfiles('ChickenSoup')
getfiles('InstantTomatoSoup')
getfiles('BroccoliSoup')
getfiles('CoffeeCookies')
getfiles('BakingSoda')
getfiles('Sweetener')
getfiles('BakingVanilla')
getfiles('ChocoIcing')
getfiles('NutellaGo')
getfiles('StrawberryPorridge')
getfiles('OrgFruitTea')
getfiles('OrgHerbTea')
getfiles('WhippedCream2')
getfiles('Marjoram')
getfiles('Curry')
getfiles('Paprika')
getfiles('TomatoHerbSauce')
getfiles('ChocSticks')
getfiles('ChocSticks2')
getfiles('Peanuts')
getfiles('Peanuts2')
getfiles('InstantSauce2')
getfiles('Peas')
getfiles('HerbSalt')
getfiles('SoftCheese')
getfiles('BathDetergent')
getfiles('ChocMarshmallows')
getfiles('CokePlasticSmall')
getfiles('CokePlasticLarge')
getfiles('VitalisCereals')
getfiles('SmacksCereals')
getfiles('Sprudelflasche')
getfiles('Wineglass')
getfiles('Waterglass')
getfiles('SmallGlass')
getfiles('Glassbowl')
getfiles('Pitcher')
getfiles('Sprayflask')
getfiles('InstantSauce')
getfiles('ToyCarYelloq')
getfiles('GreenCup')
getfiles('FlowerCup')
getfiles('MelforBottle')
getfiles('CokePlasticSmallGrasp')
getfiles('RedCup')
getfiles('CatLying')
getfiles('CatSitting')
getfiles('Clown')
getfiles('Dog')
getfiles('Dwarf')
getfiles('Fish')
getfiles('Heart1')
getfiles('LetterP')
getfiles('Moon')
getfiles('Pony')
getfiles('Seal')
getfiles('Tortoise')
getfiles('CoffeeBox')

print 'done'