function [gpModel, predShape, testIndices] = ...
    select_active_set(shapeParams, trainingParams)

method = trainingParams.activeSetMethod;
if strcmp(method, 'Random') == 1
    [gpModel, predShape, testIndices] = ...
        select_active_set_random(shapeParams.points, shapeParams.tsdf, ...
        trainingParams.activeSetSize, trainingParams.numIters);
elseif strcmp(method, 'Subsample') == 1
    [gpModel, predShape, testIndices] = ...
        select_active_set_subsample(shapeParams.points, shapeParams.tsdf, ...
        trainingParams.activeSetSize, trainingParams.numIters);
elseif strcmp(method, 'Entropy') == 1
    [gpModel, predShape, testIndices] = ...
        select_active_set_entropy(shapeParams.points, shapeParams.tsdf, ...
        trainingParams.activeSetSize, trainingParams.numIters);
elseif strcmp(method, 'LevelSet') == 1
    [gpModel, predShape, testIndices] = ...
        select_active_set_straddle(shapeParams, trainingParams);
else
    disp('Method not recognized');
    return;
end

end

